# ----------------------------------------
# PIPELINE DE CI (Continuous Integration)
# ----------------------------------------

name: Monorepo CI Orchestrator

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-service-psp:
    if: contains(github.event.head_commit.modified, 'service-psp/') || github.event_name == 'workflow_dispatch'

    uses: ./.github/workflows/reusable-build-push.yml

    with:
      service-path: service-psp
      image-name: service-psp-app
      dockerhub-repo: pix-example-tdd

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}