# ----------------------------------------
# PIPELINE DE CI (Continuous Integration)
# ----------------------------------------

name: Monorepo CI Orchestrator

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-service-psp:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(join(github.event.commits.*.modified, ' '), 'service-psp/')

    uses: ./.github/workflows/reusable-build-push.yml

    with:
      service-path: service-psp
      image-name: service-psp-app
      dockerhub-repo: pix-simulator

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}